### ISSUE TITLE
resepect postcss plugins?

### ISSUE THREAD

**Issue by asaf** [LXSMNSYC/solid-styled#24]
Hey,

I have a Vite based project with `postcss.config.cjs` that have some plugins,
Since this package is postcss based, would it be possible to respect the postcss plugins as well?

Thanks.

**Comment by lxsmnsyc** [comment]
It's actually no longer postcss-based, see: https://github.com/lxsmnsyc/solid-styled?tab=readme-ov-file#css-processing

But, if it was still in postcss, there's no room for plugins to be supported because that requires async processing, which is not possible because Babel can only run synchronously. A lot of people who tried this had implemented a solution that isn't universal (the solution being running the async task on a separate process and making it so that it runs sync on the main process), so I never really reconsidered it.

**Comment by asaf** [comment]
Fair enough, I personally needed the custom media queries and nesting which seems to be supported in LightningCSS,

I get: `[plugin:solid-styled] custom media query --foo is not defined`, I tried ti define them in my root component's using `@global` but it doesn't wok (maybe related to https://github.com/lxsmnsyc/solid-styled/issues/18)


Thanks for the great work, I like the _style_ of this plugin!

**Comment by lxsmnsyc** [comment]
Yeah I'll give this a maintenance run again. The thing is, I'm not sure if LightningCSS has already fixed the said issue.

**Comment by asaf** [comment]
I'm closing this in favor of #18
